# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.TextField()),
                ('name', models.TextField()),
                ('place', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('image_path', models.ImageField(upload_to='')),
                ('distance_near_univ', models.TextField()),
                ('price_range', models.TextField()),
            ],
        ),
    ]
