# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='image_path',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
