# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 08:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moim', '0005_auto_20170226_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applier',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Length has to be 11 & Only number', regex='^\\d{11}$')]),
        ),
    ]
