# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moim', '0006_auto_20170303_0857'),
        ('moim', '0007_auto_20170303_0721'),
    ]

    operations = [
    ]
